- name: Create cluster
  linode.cloud.lke_cluster:
    label: "{{ cluster_label }}"
    region: "{{ cluster_dc }}"
    k8s_version: "{{ cluster_version }}"
    node_pools:
    - type: "{{ cluster_node_plan }}"
      count: "{{ cluster_nodes }}"
    state: present

- name: Fetch Kubeconfig
  linode.cloud.lke_cluster_info:
    label: "{{ cluster_label }}"
  register: output
  retries: 20
  delay: 30

- name: Create Kubeconfig directory if it does not exist
  file:
    path: /root/.kube/
    state: directory

- name: Save Kubeconfig to a File
  copy:
    content: "{{ output.kubeconfig | b64decode }}"
    dest: /root/.kube/config

- name: Create a Kubernetes Namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: mynamespace