
#Helm setup
- name: Installing Helm
  block:
  - name: Download Helm GPG key
    get_url:
      url: https://baltocdn.com/helm/signing.asc
      dest: /tmp/helm-signing.asc
  - name: Import Helm GPG key
    shell:
      cmd: cat /tmp/helm-signing.asc | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null
  - name: Install transport packages
    apt:
      name: apt-transport-https
      state: present
  - name: Determine architecture
    command: dpkg --print-architecture
    register: architecture
  - name: Configure Helm repository
    blockinfile:
      path: /etc/apt/sources.list.d/helm-stable-debian.list
      block: |
        deb [arch={{ architecture.stdout }} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
      create: yes
  - name: Update apt package cache
    apt:
      update_cache: yes
  - name: Install Helm
    apt:
      name: helm
      state: present

#LKE setup
- name: Create cluster
  linode.cloud.lke_cluster:
    label: "{{ cluster_label }}"
    region: "{{ cluster_dc }}"
    k8s_version: "{{ cluster_version }}"
    node_pools:
    - type: "{{ cluster_node_plan }}"
      count: "{{ cluster_nodes }}"
    state: present

- name: Fetch Kubeconfig
  linode.cloud.lke_cluster_info:
    label: "{{ cluster_label }}"
  register: output
  retries: 20
  delay: 30

- name: Create Kubeconfig directory if it does not exist
  file:
    path: /root/.kube/
    state: directory

- name: Save Kubeconfig to a File
  copy:
    content: "{{ output.kubeconfig | b64decode }}"
    dest: /root/.kube/config

#Vault Setup

- name: Create a Kubernetes Namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: vault

- name: Pull Vault helm repo
  git:
    repo: https://github.com/hashicorp/vault-helm.git
    dest: /tmp/k8s-vault/ansiblePlaybook/vault-helm

- name: Deploy Vault on with local values
  kubernetes.core.helm:
    name: vault
    chart_ref: /tmp/k8s-vault/ansiblePlaybook/vault-helm
    release_namespace: vault
    values_files:
    - /tmp/k8s-vault/ansiblePlaybook/vault-helm/values.yaml

- name: Check RC status of command executed
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault operator init
  register: command_output
  retries: 30
  delay: 10
  ignore_errors: True


- name: Save vault config to a File
  copy:
    content: "{{ command_output.stdout }}"
    dest: /root/vault

#External secrets setup

- name: Create a Kubernetes Namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: external-secrets

- name: Add external-secrets chart repo
  kubernetes.core.helm_repository:
    name: external-secrets
    repo_url: "https://charts.external-secrets.io"

- name: Deploy External-secrets chart using values files on target
  kubernetes.core.helm:
    name: external-secrets
    chart_ref: external-secrets/external-secrets
    release_namespace: external-secrets