- name: Create cluster
  linode.cloud.lke_cluster:
    label: "{{ cluster_label }}"
    region: "{{ cluster_dc }}"
    k8s_version: "{{ cluster_version }}"
    node_pools:
    - type: "{{ cluster_node_plan }}"
      count: "{{ cluster_nodes }}"
    state: present

- name: Fetch Kubeconfig
  linode.cloud.lke_cluster_info:
    label: "{{ cluster_label }}"
  register: output
  retries: 20
  delay: 30

- name: Create Kubeconfig directory if it does not exist
  file:
    path: /root/.kube/
    state: directory

- name: Save Kubeconfig to a File
  copy:
    content: "{{ output.kubeconfig | b64decode }}"
    dest: /root/.kube/config

#Vault Setup

- name: Create a Kubernetes Namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: vault

- name: Pull Vault helm repo
  git:
    repo: https://github.com/hashicorp/vault-helm.git
    dest: /root/vault-helm

- name: Deploy Vault on with local values
  kubernetes.core.helm:
    name: vault
    chart_ref: /root/vault-helm
    release_namespace: vault
    values_files:
    - /root/vault-helm/values.yaml

- name: Check RC status of command executed
  k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault operator init
  register: command_output
  ignore_errors: True


- name: Save vault config to a File
  copy:
    content: "{{ command_output.stdout }}"
    dest: /root/vault

#External secrets setup

- name: Create a Kubernetes Namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: external-secrets

- name: Add external-secrets chart repo
  kubernetes.core.helm_repository:
    name: external-secrets
    repo_url: "https://charts.external-secrets.io"

- name: Deploy External-secrets chart using values files on target
  kubernetes.core.helm:
    name: external-secrets
    chart_ref: external-secrets/external-secrets
    release_namespace: external-secrets