# linode ansible playbook
- name: K8s/vault setup
  hosts: localhost
  connection: local
  gather_facts: true
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/linode/vars
  roles:
    - k8s_tools
    - lke
    - vault
